# Generated by Django 4.2 on 2023-05-02 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('fun_fact', models.CharField(blank=True, max_length=1000, null=True)),
                ('qrcode_filepath', models.ImageField(blank=True, upload_to='qrcodes')),
                ('location_description', models.CharField(max_length=10000, unique=True)),
                ('location_image', models.ImageField(default='../media/locations/default.jpg', upload_to='locations/')),
                ('location_badge', models.ImageField(default='../media/locations/default.jpg', upload_to='badges/')),
            ],
        ),
    ]
