# Generated by Django 4.2 on 2023-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='fun_fact',
        ),
    ]
